### ISSUE TITLE
Bug: Armor Master (mythic ability) not removing max dexterity bonus from armors

### ISSUE THREAD

**Issue by FailxFlail** [Vek17/WrathMods-TabletopTweaks#103]
As title, noticed it while using heavy armor.

**Comment by Vek17** [comment]
Are you encumbered? This is the most common issue I see when this is reported. If not can you give me more details of what is happening here.

**Comment by Lord451125** [comment]
I was going to report the same thing and that was exactly it.  Forgot how wimpy my dude was.  Thank you.

**Comment by Dhraiden** [comment]
And I as well had just come here to ask about the same: I had Woljif take it, but it did not seem to allow for a bonus from his +9 Dex Mod, until I realized it was just a [matter of shedding encumbrance](https://i.imgur.com/pGvWVjn.png). 

**Thanks** for making this great mod, Vek!
