### ISSUE TITLE
I think that Loremaster is a bit broken for Oracle at least. It doesn't give CL at all.

### ISSUE THREAD

**Issue by ludidodo** [Vek17/WrathMods-TabletopTweaks#115]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vek17** [comment]
Hm, looks like owlcats work on divine books is incomplete. I didn't touch this in my initial fix because it had already seemed function initially.

**Comment by Vek17** [comment]
This should be fixed in 1.3.1, BUT the fix is not retroactive.
