### ISSUE TITLE
Bug: Vanguard slayer doesn't qualify for extra slayer talent feat

### ISSUE THREAD

**Issue by Redicular** [Vek17/WrathMods-TabletopTweaks#118]
**Describe the bug**
The slayer archetype (vanguard) apparently has a unique version of the class feature "slayer talents", this is preventing it from qualifying for the modded feat: extra slayer talents

**To Reproduce**
Level vanguard to 7+ attempt to take extra slayer talent

**Expected behavior**
either a separate feat for vanguard slayer talent, or vanguard being able to select the generic one

**Screenshots**
![image](https://user-images.githubusercontent.com/90139107/134778640-c4b9d6b1-fc4b-472f-9caa-5c4cfbc6e565.png)

**Comment by Vek17** [comment]
Oh, I see what is going on here, Will be fixed in 1.3.2

**Comment by Vek17** [comment]
This is now fixed
