### ISSUE TITLE
Arueshalae still comes with favored enemy-demons of magic

### ISSUE THREAD

**Issue by lanis404** [Vek17/WrathMods-TabletopTweaks#135]
When you first recruit Arueshalae, even early, she's already level 8 and has 2 ranks in favored enemy-demons of magic instead of outsiders. Is there a way to change that?

**Comment by derickso** [comment]
I read that Outrider favored enemy doesn't do anything currently

**Comment by Crowhazard** [comment]
Tbh that is a dumb change they did cause of "balance" imo it should just be like in pnp choose what type of outsider.
Outsider (Evil) and (Chaotic) is already narrow enough for demons.

**Comment by lanis404** [comment]
would it be too overpowered if she had her tabletop stats as well you think?

**Comment by Vek17** [comment]
This isn't a bug, all favored enemy demons function as favored enemy outsider now and exist solely for existing build compatibility. Continue taking ranks in them to progress favored enemy. Descriptions are updated in the next version.
