### ISSUE TITLE
Bolster Spell Metamagic

### ISSUE THREAD

**Issue by rjoffr07** [Vek17/WrathMods-TabletopTweaks#138]
**Describe the bug**
Bolster Spell Metamagic additional splash damage doesn't work anymore (the  2 dmg per die roll around the target).

**To Reproduce**
Cast a spell modified by bolster magic like "Magic Missile" on an enemy target near another one.

**Expected behavior**
Enemies withing 5 ft. of the target should receive 2 damage per die roll of the spell.

**Comment by Vek17** [comment]
Looks like I broke this when trying to remove friendly fire from it. Will be fixed in the next release.

**Comment by Vek17** [comment]
Limited fix is in 1.3.6

**Comment by rjoffr07** [comment]
It's mostly fixed, but i just found out that magic missile only applies 1 instance of AoE damage from bolster, while it should apply it as many time as there is missiles.

It also probable that it similarly doesn't work with multiple ray attacks from spells such as "Scorching Rays" and "Hellfire Rays".
