### ISSUE TITLE
"Shatter defenses now works like tabletop"?

### ISSUE THREAD

**Issue by Amariithynar** [Vek17/WrathMods-TabletopTweaks#141]
Shatter Defenses, according to the tooltip in-game, already works as it does in tabletop; if you hit a shaken, panicked, or frightened combatant, they are flatfooted to all your attacks until the end of your next turn. How is this change actually changing how the feat works?

**Comment by KirilCvKirilov** [comment]
Tooltip != Implementation. Afaik, in tabletop the enemy is considered flat-footed after your first hit, while in the game they are already flat-footed already during your first hit.

**Comment by Vek17** [comment]
What KirilCvKirilov said. This feat now requires you to hit the target non flat footed before they become flat footed.

**Comment by Amariithynar** [comment]
> Tooltip != Implementation. Afaik, in tabletop the enemy is considered flat-footed after your first hit, while in the game they are already flat-footed already during your first hit.

That's why I asked how it's changing how it works, because I haven't been abusing it, similar to how I didn't abuse Bolster before when it was bugged. :P Thank you for the clarification.
