### ISSUE TITLE
Ability to toggle rules

### ISSUE THREAD

**Issue by Lord451125** [Vek17/WrathMods-TabletopTweaks#144]
I love a whole bunch of things you've done an added, but there are a few of them that I just don't like. 
 Specifically the limits on the Extra Mythic Power feat.  I know it's described in the ability, but this limits a lot of potentially interesting builds and if a player doesn't like the idea or thinks it's cheating, everybody can choose not to use it.  

It's great to have options for things like this, but I don't know how much infrastructure change it might take to add something like this on the various features.  

Thank you.

**Comment by Vek17** [comment]
this is already disablable in the config fixes under user settings.

**Comment by Lord451125** [comment]
Thanks.  I'll go check it out and I appreciate the response.

**Comment by Lord451125** [comment]
Just to make sure I understand, this'd be updating the .json and .cs files in the various sub directories?  Or is there a config menu I just haven't found?
