### ISSUE TITLE
Add Bolster Spell magic to Favorite Metamagic Mythic Ability

### ISSUE THREAD

**Issue by derickso** [Vek17/WrathMods-TabletopTweaks#149]
**Is your feature request related to a problem? Please describe.**
The Favorite Metamagic Mythic Ability does not currently allow you to select Bolster Spell Metamagic

**Describe the solution you'd like**
Add Bolster Spell to Favorite Metamagic so it reduces it to +0 level increase

**Additional context**
![image](https://user-images.githubusercontent.com/6112623/135417683-2ec47387-6fb3-417b-a992-fae46fa6f09f.png)

**Comment by Vek17** [comment]
I keep forgetting to put this into a release... As soon as I remember it will be enabled.

**Comment by TKDancer** [comment]
maybe later down the line if you get the time would it also be possible to make a favorite metamagic - selective? would heighten having it also make sense? idk

**Comment by derickso** [comment]
> 
> 
> I keep forgetting to put this into a release... As soon as I remember it will be enabled.

![image](https://user-images.githubusercontent.com/6112623/135737616-7230615f-8bcd-44a3-8aab-9c08fb03f52b.png)

**Comment by Vek17** [comment]
This is now in the next build, but not 1.4.0

**Comment by derickso** [comment]
+1
