### ISSUE TITLE
Incompatible with 1.0.1c?

### ISSUE THREAD

**Issue by Eonsim** [Vek17/WrathMods-TabletopTweaks#16]
Getting crashes when trying to load a save from TTweaks 1.0.3 with the current Wrath release 1.0.1c.
Is there a fix for this with regards to the TTweaks?

TT1.0.6 doesn't seem to fix the issue.

**Comment by Vek17** [comment]
I need more details than this to know if this mod is causing the problem. When are these crashes happening?

Additionally can you send me you Player.log after a crash? It should be at the following path
`%userprofile%\AppData\LocalLow\Owlcat Games\Pathfinder Wrath Of The Righteous`

**Comment by Eonsim** [comment]
This is happening when attempting to load a save made with TT1.0.3 in WoR 1.0.1c.
[Player.log](https://github.com/Vek17/WrathMods-TabletopTweaks/files/7119693/Player.log)

The game happily loads saves made before the install of TT1.0.3.

**Comment by Vek17** [comment]
You currently have the mod disabled and your save relies on the mod being enabled. Enable the mod and then load.

```
[Manager] Parsing mods.
[Manager] Reading file 'C:\Program Files (x86)\Steam\steamapps\common\Pathfinder Second Adventure\Mods\TabletopTweaks\Info.json'.
[Manager] Sorting mods.
[Manager] Loading mods.
[TabletopTweaks] To skip (disabled).
[Manager] FINISH. SUCCESSFUL LOADED 1/1 MODS.
```

The exact failure is that it is trying to load the ElfAbilityModifiers feature and since the mod is not loaded that feature does not exist.

**Comment by Eonsim** [comment]
Okay that's bizare. The mod-manager claimed the mod was loaded, I've reloaded and restarted it and now it's started to load again...

I'm not sure what's happened there, mod-manager seemed to be happy...

**Comment by Vek17** [comment]
So things are now working correctly then?

**Comment by Eonsim** [comment]
It seems to be it's loaded into the map rather than crashing at 5%, I'm a tad confused.
I'd tried it several times with the mod 'supposed' to be enabled both with 1.0.3 and 1.0.6 and it crashed. Now couple more attempts and it has worked...
