### ISSUE TITLE
Hello, thank you for a wonderful mod. I am having issues since the last update. I am not able to create scrolls while resting. I currently only have three mods: Toybox, Tabletop Tweaks and Fast travel. Thanks in advance for your help.

### ISSUE THREAD

**Issue by jdgen11** [Vek17/WrathMods-TabletopTweaks#163]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Vek17** [comment]
Can you expand upon this issue? I am able to craft scrolls without any issues.

**Comment by jdgen11** [comment]
I just recently noticed that my scrolls were not showing up in my items
menu.
When I camp outside or in my room and I create scrolls they do not appear
in my items. The screen says I passed all the DC checks, sometimes I make
multiple scrolls. Not sure how that works. Specifically level seven and
level six spells. Level two spells seem to be working I haven't tried any
other levels. I have all of the components and the crafting table as well
as the scroll creating feats. I think the problem  occurred with this last
update.
I've tried different npcs with the same spells but still too no avail.
Thanks for you help!
Hopefully that helps. I can't think of any other factors that would
contribute to this problem.

**Comment by Amariithynar** [comment]
Are you sure you actually created the scrolls and didn't just succeed on one of the multi-day steps to create it?

**Comment by jdgen11** [comment]
I guess that could be, maybe I don't understand how it works then. It only
gets to one. I thought that was the number of scrolls that were made.

**Comment by Amariithynar** [comment]
> I guess that could be, maybe I don't understand how it works then. It only gets to one. I thought that was the number of scrolls that were made.

Nope, on the creation section where it shows what's being made, the "1", "2", "3" etc in order are the number of rests you need to do to make the scroll or potion. All the lower level ones only take 1 day, which is why they only show "1" for them.
