### ISSUE TITLE
Sorcerer bloodline DR stacking

### ISSUE THREAD

**Issue by Mira132** [Vek17/WrathMods-TabletopTweaks#182]
**Describe the bug**
Not sure if this is intended behaviour or not, but, with an undead bloodline sorcerer, I got the one of us ability with bloodline ascendance, second bloodline aberrant and another bloodline ascendance to get aberrant form. I end up with two DR 5/- showing they don't stack.

**To Reproduce**
1. Pick aberrant or undead bloodline sorcerer.
2. Use mythic path to get the second bloodline and the level 20 ability from both.

**Comment by Vek17** [comment]
This is technically working as intended
