### ISSUE TITLE
Can't load alongside Fast Travel mod

### ISSUE THREAD

**Issue by Mira132** [Vek17/WrathMods-TabletopTweaks#205]
**Describe the bug**
I tried installing fast travel, but am unable to get past the initial loading screen. After trying different mod combinations, I found out I can have either TabletopTweaks or Fast Travel installed. Having both prevents me from loading the game.

**To Reproduce**
1. install both TabletopTweaks and Fast Travel
2. Launch the game

**Expected behavior**
There should be no issues loading both mods at once.

**Additional context**
Still have the problem after uninstalling all mods and making fresh installs of both mods. Also tried with TabletopTweaks mod versions as far back as 1.3.7.

Pastebin of player.log: https://pastebin.com/kwftSpic
Pastebin of GameLogFull: https://pastebin.com/Gr1fQPtd

**Comment by Vek17** [comment]
I mean that mod is closed source so i can't look there and all I can tell
you is that TTT is failing to read that setting in the log file.
