### ISSUE TITLE
Obsolete patches

### ISSUE THREAD

**Issue by Truinto** [Vek17/WrathMods-TabletopTweaks#210]
I think the methods PatchSlumber() and PatchRestlessSlumber() don't do anything.

I datamined the blueprints and found that the SpellDescriptorComponent is already set correctly to "MindAffecting, Compulsion, Sleep, Hex". Maybe this was fixed in a game update.

**Comment by Vek17** [comment]
Probably has, I haven't cleaned up all of the patches from beta yet
