### ISSUE TITLE
Profane Ascension get dispelled 

### ISSUE THREAD

**Issue by solo16** [Vek17/WrathMods-TabletopTweaks#218]
After the fight with Baphomet profane ascension got dispelled I believe it is a bug related to TTT? I'm using the latest TTT 1.6.1.

Thanks!

**Comment by Vek17** [comment]
That should be impossible... Profane Ascension is a feature not a buff so should not be subject to dispel. I also did not touch it :(

**Comment by CantripN** [comment]
It's removed if you fight against the commands of Nocticula and win. You can't disobey her and keep it.

**Comment by solo16** [comment]
Oh ic thanks for the information!
