### ISSUE TITLE
possible to separate?

### ISSUE THREAD

**Issue by tryadelion** [Vek17/WrathMods-TabletopTweaks#22]
Is there any way to have just the missing traits / bloodlines without the modifications on the default ones?

**Comment by Vek17** [comment]
You should be able to just disable the options you do not want in the config. That said the modifications to bloodlines are merely making them correctly interact with things like dragon disciple not the removal of any abilities or balance changes.

**Comment by tryadelion** [comment]
will try the settings, thanks! was asking cause i play the game as a relax tool and it feels like some changes would make the game harsher and more challenging

**Comment by Vek17** [comment]
Hard to really say if the game ends up harder or easier with everything enabled. The intent is not to drastically alter the balance but to remove undocumented behavior mostly, though in some cases that can result in small changes of power.

**Comment by tryadelion** [comment]
I don't se a config option on the Unity Mod Manager menu, should i configure directly on the Json files?

**Comment by Vek17** [comment]
yes the json handles the configs
