### ISSUE TITLE
Request to fix Coup de Grace

### ISSUE THREAD

**Issue by StefanLorre** [Vek17/WrathMods-TabletopTweaks#23]
"As a full-round action, you can use a melee weapon to deliver a coup de grace (pronounced “coo day grahs”) to a helpless opponent. You can also use a bow or crossbow, provided you are adjacent to the target.

You automatically hit and score a critical hit. If the defender survives the damage, he must make a Fortitude save DC 10 + damage dealt) or die. A rogue also gets her extra sneak attack damage against a helpless opponent when delivering a coup de grace."

As stated by RAW.

In-game, however, the Coup de Grace has some random calculation for the Fort Save that is nowhere near the actual rules. I have no idea what it uses to calculate.

Example:

![Coup 3](https://user-images.githubusercontent.com/51094920/132570491-946d3fb5-b40f-4900-b528-c4c633269031.PNG)
![Coup](https://user-images.githubusercontent.com/51094920/132570493-47320a24-228b-4a95-9fa6-6cb49f4e4fd3.PNG)
![Coup 2](https://user-images.githubusercontent.com/51094920/132570990-12b5efed-fdfe-46cb-8438-77ef296f8765.PNG)

The DC should be 10 + 44, as stated by RAW, but somehow it ends up being 29? 

29 doesn't make any sense tho, even if you'd assume it's not taking the Crit damage into account, cause that's not even half.

I'd love to have you take a crack at this, as it's massively annoying to set up a Coup de Grace and then have basic enemies automatically succeed their saves cause they have +20 Fort Save or whatever.

**Comment by Vek17** [comment]
Already an issues for this: #20
