### ISSUE TITLE
Bug: Steel Headbutt (assumably) caused multiple unarmed strikes appeared out of nowhere. 

### ISSUE THREAD

**Issue by Lockindal** [Vek17/WrathMods-TabletopTweaks#231]
No idea how this happened, but even a respec doesn't fix it (as you can see from this level 1 screenie)

It doesn't appear for any other unit. I am GUESSING it came from "Steel Headbutt" somehow, since he has that prior to me trying to respec him.

I realize this is probably very difficult to reproduce, I will happily send you my save.

![image](https://user-images.githubusercontent.com/91929279/136907100-bf975754-5d9f-49ef-bfee-d9961005d62c.png)

Why I think it's steel headbutt that caused it:
![image](https://user-images.githubusercontent.com/91929279/136907165-573cc2d3-424b-47c1-b0a8-ccf161d1a513.png)

Mods installed:
![image](https://user-images.githubusercontent.com/91929279/136906563-c60518b3-df65-4263-b6ef-e49747b25d5f.png)

Since this is a character problem, even uninstalling mods isn't likely to bring him to 'normal' state which makes it harder to eliminate your mod.
I didn't see anything in your patch notes that would address this, but i was on 1.06a before updating to the latest (per the UMM screenshot)

**Comment by Lockindal** [comment]
That's odd. It definitely attacked with them in that screen i posted.
But if they don't attack I guess I'll try to ignore it.

No idea how they even got there though.
And, I did post additional saves - it started with 1, then grew to two, and kept getting more throughout drezen somehow. lol

**Comment by Vek17** [comment]
I'll have to see if I can get more of the broken limbs to be added. It
lookes like the steel headbutt one was working correctly at a glance but
more testing is needed.

**Comment by TwiceTested** [comment]
If it helps, I get the same issue on my skald with Animal Bite giving people extra bites.  Currently in Act 1 and Camilla now has 5 bite attacks without rage going...

I haven't installed TabletopTweaks yet either, so this is a bug from the main game.

**Comment by Lockindal** [comment]
No, I just ignore it now and play the game with broken natural attacks (that disappear and re-appear at whatever whim they want). Based on what the poster above said, I don't even know that it has anything to do with your mod. Sounds like there's some bug in the base game.

**Comment by TwiceTested** [comment]
I can get extra bite attacks by turning inspire rage off and back on before the lingering song runs out.  I've attached screenshot and my save file.  Had toybox running with all d20 rolls as a 1 for everyone so I could test it out.

Oddly, I seem to be able to re-set the bites by changing the equiped weapon set, from 1 to 2 for example. (have rapier in set one, unarmed in set 2, and switch between them).  After the re-set I have to do the dancing inspire rage again to get all the bites.  For the Steelheadbutt, do you lose the extra one after switching weapons?

**Comment by pheonix99** [comment]
I haven't seen excess steel headbutt attacks lately - thanks.

**Comment by Vek17** [comment]
It seems like my changes are working, I also haven't seen additional clones show up in my current game.
