### ISSUE TITLE
Feature/Bug Aeon changes/settings

### ISSUE THREAD

**Issue by nfree25** [Vek17/WrathMods-TabletopTweaks#245]
Not sure if its just me, but Aeon changes seems to be missing from the json(s).
I tried generating new ones, no luck.

Also, if you are still working on aeon, could you fix aeon bane on spells? Currently it makes 2 rolls for SR, taking the lower result. 
https://media.discordapp.net/attachments/815735034514112512/898426541959151616/unknown.png
https://media.discordapp.net/attachments/815735034514112512/898440695759650846/unknown.png

**Comment by Dhraiden** [comment]
Thank you for making the fix so quickly, Vek.
