### ISSUE TITLE
Persistent Spell metamagic cannot be applied to "Bestow Curse" and "Greater Bestow Curse"

### ISSUE THREAD

**Issue by chessandy** [Vek17/WrathMods-TabletopTweaks#252]
Issue: The metamagic feat Persistent Spell cannot be applied to the spells: "Bestow Curse" and "Greater Bestow Curse". 

Description: When opening the metamagic editor in the spellbook and after selecting e.g. Bestow Curse the metamagic feat Persistent Spell is greyed out. (Other metamagic feats can be applied to these spells) The caster level of the character is high enough to use the feat on both of these spells. (caster level 19 and can cast level 9 spells). I also see no reason from a rules perspective that the feat cannot be applied to these spells.

Expected: Persistent Spell metamagic can be applied to "Bestow Curse" and "Greater Bestow Curse"

**Comment by Vek17** [comment]
This will be fixed in 1.11.0
