### ISSUE TITLE
Bugfix setting missing for classes with only base or archetype functions

### ISSUE THREAD

**Issue by pheonix99** [Vek17/WrathMods-TabletopTweaks#255]
In the mod settings menu, classes like alchemist that don't have both base and archetype fixes don't show.

Fiix by changing the OR to an AND in the initial conditional in UMMSettingsUI.NestedSettingGroup(string name, TabLevel level, IDisableableGroup rootGroup, params (string, SettingGroup)[] nestedGroups).

**Comment by Vek17** [comment]
fixed
