### ISSUE TITLE
Loremaster spell secret not working

### ISSUE THREAD

**Issue by Mira132** [Vek17/WrathMods-TabletopTweaks#257]
**Describe the bug**
When picking a loremaster spell secret, the list of spells that can be selected is the same as the base class's spellbook. For example, an arcanist taking spell secret can take any spell on the arcanist spell list but none of those only available on the cleric spell list like cure or inflict spells.

Found issue on game version 1.1.0 and mod version 1.9.1b

**To Reproduce**
1. Level up a spellcaster class to be able to pick loremaster.
2. Level up loremaster to gain a secret and pick one of the other classes spell list.
3. Notice the spell selection is that of your base class, not the selected class secret.

**Comment by Vek17** [comment]
Looks like I messed up which list was used when fixing the last of the lore master edge cases, will be fixed in the next build
