### ISSUE TITLE
Magus spell levels 4-6, Intensify Spell metamagic

### ISSUE THREAD

**Issue by semiliterate** [Vek17/WrathMods-TabletopTweaks#261]
Currently the only arcane touch spell implemented for these levels seems to be Touch of Slime, which is not on the magus spell list. 

The system has candidates available such as spell blending Calcific Touch or Hellfire Lash at level 4, but the Magus spell list is light on touch spells at high levels in the SRD as well - at Magus level 5 there's Teleport and Corrosive Consumption, for example.

Given that the class up-front bills itself as working particularly well with touch spells and it's such an integral part of the class theme, there should probably be some options to do that even in the latter part of the game - possibly implementing one or two of these touch spells.

The usual pen and paper option however isn't the limited high level touch spells - it's the Intensify Spell metamagic, which allows preparing lower level touch spells like Shocking Grasp and Vampiric Touch in higher level spell slots to increase their damage dice caps. As it is, late-game Maguses are trading on Elemental Barrage and not their class abilities, which is a weird choice for a class who has so many levels improving their signature Spell Combat and Spellstrike.

**Comment by nukularpower** [comment]
Even in Kingmaker with COTW i was boggled with how few touch options there are.   Really seems to me that there shouldnt be a seperate Eldritch Archer, just a magus that can use melee AND ranged spellstrikes - what sense does it even make that they can only do it with certain weapons

**Comment by Vek17** [comment]
this will be in 1.11.0 which will be out for WotR 1.2.0
