### ISSUE TITLE
Focused Weapon does not count Magus Fighter Training feat

### ISSUE THREAD

**Issue by solo16** [Vek17/WrathMods-TabletopTweaks#281]
My MC is a eldritch archer which at lv10 i receive Fighter Training which count half of magus level as fighter so my question is does Focused Weapon intentionally ignore that and it is a hard requirement to actually have a fighter class in order for the feat to work?

Thank you so much for the mod btw!!!

**Comment by Vek17** [comment]
because he has hellknight levels.

> The fighter selects one weapon for which he has Weapon Focus and that belongs to the associated fighter weapon group. The fighter can deal damage with this weapon based on the damage of the warpriest’s sacred weapon class feature, **treating his fighter level as his warpriest level**. The fighter must have Weapon Focus with the selected weapon in order to choose this option.
