### ISSUE TITLE
Metamagic Rager makes Extend Spell of Transmutation Supremacy  not working

### ISSUE THREAD

**Issue by Alexia2333** [Vek17/WrathMods-TabletopTweaks#284]
I find we I have Transmutation Supremacy the extend spell effect is not work.
I tested stop function and when i stop Metamagic Rager(under Added Content-Archetypes) extend spell work as the buff time doubled.

**Comment by Vek17** [comment]
This should be cleaned up in v1.9.6 with the rebuilt metamagic rager.
