### ISSUE TITLE
Stormlord's Resolve Should Work with Arcanist

### ISSUE THREAD

**Issue by jp-bennett** [Vek17/WrathMods-TabletopTweaks#286]
It's a fairly minor thing, but it really seems like the Stormlord's Resolve bracers should give an Arcanist the extra spells, since the Arcanist casts like a spontaneous caster.

**Comment by Vek17** [comment]
But it does?

**Comment by jp-bennett** [comment]
> But it does?

*launches the game again to check*

Nope. It adds the spells to the Arcanist's spellbook, which is pretty obviously not correct.

**Comment by Vek17** [comment]
No that is very correct, arcanist has to prepare known spells which they then cast spontaneously. They get added as spells known but still have to follow arcanist rules.

**Comment by Carden-Gixoth** [comment]
Vek is correct. You prepare spells ahead of time like a Wizard (sort of), but then cast them like a Sorcerer. Lets say you can only prepare 3 spells for level 3, and you have Fireball, Haste, and Lightning Bolt prepared as an Arcanist. You also have, lets say, 10 spell slots of 3rd level. You can then choose to cast 10 Fireballs, or 5 Fireballs, 3 Haste and 2 Lightning Bolts, or any combination of the 3 spells, so long as you do not go over the 10 spells of third level a day that you are allotted. Arcanists are very weird like that, but Vek is correct that it's working properly.

**Comment by jp-bennett** [comment]
@Vek17 @Carden-Gixoth Yes, I understand how Arcanists work. The question is how this item interacts with the Arcanist. In Pathfinder specific trumps general, and the item has a very specific description of what it does. It does not say that it adds the spells to a caster's spellbook, it says "it grants them the ability to cast the following". If the item says it adds to known spells, I would agree, but it does not. It's a huge nerf to the utility of the item, when used by an Arcanist.
