### ISSUE TITLE
Quick Study does nothing

### ISSUE THREAD

**Issue by DeadMor0z** [Vek17/WrathMods-TabletopTweaks#293]
**Describe the bug**
If Arcanist's "Prepared Spell UI" is turned on, when using "Quick Study" to prepare arcanist spell, reservoir points are consumed, but spell is not prepared. 

**To Reproduce**
Try to "Quick Study" any 5+ lvl spell.

**Expected behavior**
New spell should be prepared and available

**Comment by Vek17** [comment]
I am unable to reproduce

**Comment by DeadMor0z** [comment]
I have a ToyBox installed and MC is multiclassed with scald and arcanist (eldritch font), so, basically it has 2 spell boooks. May be it is related somehow?

**Comment by Vek17** [comment]
Can you upload your save and give me a list of installed mods?

**Comment by DeadMor0z** [comment]
Made a bit of testing. Turned option on - everything works now. o_O
My be it is related to first install? Haven't run with this mod before.
