### ISSUE TITLE
Hosilla turning ally

### ISSUE THREAD

**Issue by Elec0** [Vek17/WrathMods-TabletopTweaks#30]
When I got to the Hosilla fight, in stage 2 when she summoned the demons she became an ally for some reason, and so I was unable to continue.
I had to restart the playthrough without TT installed, since disabling it and trying to load a save gave me an error.

Installed mods at the start of game:
* Respec Mod
* Scaling Cantrips
* Tabletop Tweaks
* Toybox
* World Crawl

After I hit the error, I uninstalled everything except Toybox & Tabletop Tweaks, no change in behavior.
Restarting the playthrough without TT let me get through the fight as normal.

**Comment by Vek17** [comment]
Do you have the save file you encountered this on? This sounds unrelated but I'll see if I can reporduce

**Comment by Elec0** [comment]
Ah, you know what? I think it was a problem with the Respec Mod that persisted after I uninstalled it.

Looking at the save files, they look bad: 
![image](https://user-images.githubusercontent.com/5119098/132923457-fbbf8a24-d07e-4726-bb5f-1629d4eee852.png)

Which I think the most recent update fixed.
