### ISSUE TITLE
Selective Metamagic working only selectively

### ISSUE THREAD

**Issue by Xyrmes** [Vek17/WrathMods-TabletopTweaks#300]
Some spells that allow for Selective Metamagic to be applied don't actually work, at least when implemented with an ongoing game. Namely spells that create an effect on the field, like Sirroco and Grease; spells like Waves of Ecstasy and Dragon's Breath still ignore party members.

I noticed it when I cast Sirroco and Domain of the Hungry Flesh, which I had previously used via Selective metamagic without issue, and they both affected my party, which they hadn't before.

I tried clearing all the spells I'd altered and redoing them, but it didn't change anything, Dragon's Breath still ignored allies but Grease and Domain of the Hungry Flesh didn't.

Hopefully, these pictures help illustrate the issue, if it wasn't already clear.

<img width="1860" alt="Sample1" src="https://user-images.githubusercontent.com/31435121/140631725-c0eb5b9c-8e9e-44e9-9714-089a3e43be88.png">
t
<img width="1860" alt="Sample2" src="https://user-images.githubusercontent.com/31435121/140631730-a6d0f575-d2bc-47ac-8fb6-b1e376329834.png">
.

**Comment by AeonicAssembler** [comment]
This is intentional. Selective Spell isn't supposed to work on spells that create an effect on the field, so one of the tweaks makes it so that it doesn't. If you still want Selective Sirocco or other spells like that, disable the Selective Spell tweak.

**Comment by Xyrmes** [comment]
> This is intentional. Selective Spell isn't supposed to work on spells that create an effect on the field, so one of the tweaks makes it so that it doesn't. If you still want Selective Sirocco or other spells like that, disable the Selective Spell tweak.

Oh, never mind then.
