### ISSUE TITLE
Bloodrager - Aberrant Bloodline - Abnormal Reach

### ISSUE THREAD

**Issue by LordInnario** [Vek17/WrathMods-TabletopTweaks#302]
Seems like abnormal reach does nothing: no impact on reach and non-reach weapon.
In same time longarm spell work just fine. And toybox reach edditing too

Find it in: 1.1.0k GOG
Full list of mode:
TTTweaks 1.9.6b
Toybox 1.4.8.1
WeponFocusPlus 1.2.1
GreatRadiance 1.00

**Comment by Vek17** [comment]
Are you bloodraging when testing this? Abnormal reach will only apply in rage.

**Comment by LordInnario** [comment]
Just retest in bloodrage - still missing.
Also try (by "always 20" from toybox) Staggering Strike bloodrage power - no sign in combat log.

Addition to mod and game vercion: play in russian local. And bloodrager have Primalist archetype.

**Comment by LordInnario** [comment]
And retry this in English local and after respec to non-archetype solo class bloodrager - still missing i,pact from both bloodline powers

**Comment by ArmeniusLaurant** [comment]
Seconded- Reach is not applying even with bloodrage.

**Comment by LordInnario** [comment]
It's suddenly start work normal - after clear reinstall game and mods. And respec from toybox mod.

**Comment by Vek17** [comment]
There is something odd going on with the rage buff not always starting.
