### ISSUE TITLE
Misspelling of "Enchantment" in steel headbutt

### ISSUE THREAD

**Issue by BarleyFlour** [Vek17/WrathMods-TabletopTweaks#309]
**Describe the bug**

**To Reproduce**
1. Go to Feature Selection as a fighter
2. Click on advanced armour training
3. last paragraph says "echantment" instead of "enchantment"

**Screenshots**
![SteelHeadbutt](https://user-images.githubusercontent.com/82173938/141492544-e961a1c0-67ed-45c0-93ec-2637b91cb9a2.png)

**Additional Context**

can be fixed by simply changing the string on line 74 of "TabletopTweaks/NewContent/FighterAdvancedArmorTrainings/SteelHeadbutt.cs"

**Comment by Vek17** [comment]
fixed in next release
