### ISSUE TITLE
Halfling Alternate Trait Bug

### ISSUE THREAD

**Issue by Ebonmark** [Vek17/WrathMods-TabletopTweaks#312]
**Describe the bug**
The Halfling alternate trait 'Blessed' references sacrificing the 'Fearless' trait in the alternate trait description, but seems to be looking at the 'Halfling Luck' trait mechanically as the actual pre-requisite and presumably trade off.

**To Reproduce**
1. Create a new halfling character and proceed to the Alternate Trait portion.
2. Select 'Hasty' and you will notice that 'Blessed' is still available despite 'Hasty' forfeiting the Fearless trait.

**Expected behavior**
'Blessed' should list 'Fearless' as the required trait and not 'Halfling Luck'

**Screenshots**

**Additional context**

**Comment by Vek17** [comment]
this should be fixed next release
