### ISSUE TITLE
Precision Critical doesn't seem to work.

### ISSUE THREAD

**Issue by Philoceratops** [Vek17/WrathMods-TabletopTweaks#330]
**Describe the bug**
Precision Critical doesn't seem to work.

**To Reproduce**
Sneak Attack dice aren't doubled on critical despite message saying the contrary.

**Comment by Vek17** [comment]
Can you give me more detail? Are you sure you have a real crit not
something where crit damage gets immuned?

**Comment by Philoceratops** [comment]
I just accidentally deleted the screenshot... :(

I have an odd number of Sneak Attack dice and it doesn't change. It shows 7d6 (x2) then result (say, 39). Weapon crits as normal.

Does it multiply the dice under the hood? I.e. game rolls 14d6, but it only shows me the result? Or should I see the dice doubled in log?
