### ISSUE TITLE
Burst damage for magus

### ISSUE THREAD

**Issue by Asaliath** [Vek17/WrathMods-TabletopTweaks#334]
Hello,

I haven't playtest much this bug but, whenever I use Electric Burst damage on my Magus the game freeze and crash. 
Disabling the burst damage prevent this to happend.
Here is my list of mods: 

![Capture](https://user-images.githubusercontent.com/96079260/145956526-6256937a-f6fa-48a2-965f-4d6aed6123c6.PNG)

**Comment by Vek17** [comment]
I am not able to reproduce this crass in my save at this time.
