### ISSUE TITLE
Loremaster secret spell selection for wizard - witch is broken (0 spell to select)

### ISSUE THREAD

**Issue by Yericus** [Vek17/WrathMods-TabletopTweaks#345]
**Describe the bug**
Loremaster secret spell selection for wizard - witch is broken (0 spell to select - contagion pre selected - still 0 spell to select when deselected contagion).

**Steps**
I made a Witch Ley Line guardian to level 8, then 5 levels in Winter Witch.
On level 13, I am trying to put a level in loremaster --> spellbook Witch --> Secret Wizard Spell / Wizard Spell - witch.

Upon clicking to select Wizard Spell / Wizard Spell - witch : The next tab (Secret) appears with Contagion already selected.
When moving to the Secret Tab, Contagion is still selected by default.

You can deselect Contagion and other spells seem select-able BUT the number displayed for selecting a spell is 0.
When selecting another spell than Contagion and moving to next tab for my witch spell selection, the secret spell tab reverts to contagion icon when the spell in normal spell tab is chosen.

**Expected behavior**
We are supposed to choose a spell from the secret tab.

**Screenshots**
1-->7
![1](https://user-images.githubusercontent.com/6996927/147629782-7dd45726-e13c-4beb-9cc2-5031867992a4.png)
![2](https://user-images.githubusercontent.com/6996927/147629787-9d4aed66-b8af-4efc-8d83-13b5fdf2ad47.png)
![3](https://user-images.githubusercontent.com/6996927/147629790-90985b0e-b5b4-4387-b0d1-a511276e6ba5.png)
![4](https://user-images.githubusercontent.com/6996927/147629793-ba414719-32f0-446c-8e7e-9f788fc46182.png)
![5](https://user-images.githubusercontent.com/6996927/147629795-e2b4a237-d4ba-4a0c-844e-e062ecd5add9.png)
![6](https://user-images.githubusercontent.com/6996927/147629798-2b2746aa-a59e-47bb-a502-973e32041df2.png)
![7](https://user-images.githubusercontent.com/6996927/147629799-a6ebd507-1644-464d-85e5-1ab37254699d.png)

**Comment by Vek17** [comment]
Can you upload the relevent save and give me your modlist so I can
reproduce.

**Comment by Yericus** [comment]
Trying to reproduce !
Doesn't happen right now leveling up from the character level, will go to inn to make the same new Merc from start.
________________________________

**Comment by Yericus** [comment]
Can't seem to be bale to reproduce it, my bad, was probably a one time thing.
