### ISSUE TITLE
"Devouring Lust" Metamagic rod is enabled by default on load - let's change that !

### ISSUE THREAD

**Issue by Yericus** [Vek17/WrathMods-TabletopTweaks#346]
**Is your feature request related to a problem? Please describe.**
I see you have fixed a few items being enabled or not when loading the game (Iomadae belt buckle stays on thanks to you for example).

One item that is annoyingly on by default when you load a game is "Devouring Lust" ; a metamagic rod you get by decree repairing a relic in the keep.

**Describe the solution you'd like**
Would it be possible for the item not to be enabled by default ?

Thank you.

**Comment by Vek17** [comment]
Fix is in 1.11.0
