### ISSUE TITLE
DR stacking issue with Angel's Unbroken ability from transformation.

### ISSUE THREAD

**Issue by pheonix99** [Vek17/WrathMods-TabletopTweaks#354]
By the Indestructible Bones precedent Angel's Unbroken DR 10/- aura should probably stack with other sources of DR X/-.

The aura is from the MR 9 transformation - it's another one of Angel's little undocumented-till-you-get-it perks like Sword Of Holy Damage.

**Comment by Vek17** [comment]
changed in 1.11.0
