### ISSUE TITLE
Elemental Barrage rebalance

### ISSUE THREAD

**Issue by Imataruto** [Vek17/WrathMods-TabletopTweaks#355]
**Is your feature request related to a problem? Please describe.**
Elemental Barrage seems to get really broken when paired with geniekind or magus, as you get a lot of d6 dices by using different elemental damages on the same round, which activates elemental barrage more than once.

**Describe the solution you'd like**
Maybe a homebrew solution to it like limiting it to activate one or two times at most would make it balanced.

**Describe alternatives you've considered**
 Something like needing to do the other elemental damages on the next turn could also ease the problem, but this solution seems too harsh.

**Comment by pheonix99** [comment]
I think the best balance fix is to make it work as designed and only trigger off spells and spell like abilities  and not weapon attacks.

This would be a tad finicky for effects like Geniekind and Firebrand that are weapon attack damage boosts implemented as extra hits but those need to be converted to not be extra hits *anyway* to keep them from proccing Bane enchants and Mark of the Sun.

**Comment by Vek17** [comment]
There is an experimental change that will be shipping in 1.11.0
In concept it is sort of a caster hybridized leading strike.

> Every time you deal elemental damage to a creature with a spell, you apply an elemental mark to it. If during the next three rounds the marked target takes elemental damage from any source with a different element, the target is dealt additional Divine damage. The damage is 1d6 per mythic rank of your character.

**Comment by Imataruto** [comment]
at least Geniekind should be fixed, as apparently you can stack it, leading to 30d6 damage per attack if all four types are used (with elemental barrage).
With two weapons/monk that's like 8*30d6
The effect should not stack with itself, I guess. So that's a fix.
