### ISSUE TITLE
Focused Weapon Not Working

### ISSUE THREAD

**Issue by Vexthecollector** [Vek17/WrathMods-TabletopTweaks#362]
As the title says, focused weapon seems to not be working. The damage is not shown in the character window and also not added on damage rolls. I have it on two different characters and it works on neither.

**Comment by Vek17** [comment]
Can you give me more context? What weapon, what levels, screenshot, etc. It works in my game when testing.

**Comment by felipearmat** [comment]
Correctly working on my pc. Remembering that the dmg is based on fighter's class level, and also that it uses the warpriest dice damage, wich changes over each 5 lvls (commonly lvl5->1d8, lvl10->1d10, lvl15->2d6, lvl20->2d8).
Tested with axe group, throwing group, bow group, close group and hammer group... need more context for shure.

**Comment by Vexthecollector** [comment]
Screenshots provided. 
Character has the focused weapon feat, but the damage for it does not seem to show up in the damage window and neither did it when testing when I was in combat. The prerequisites seem to be met. Weapon Focus and Weapon Specialization

![image](https://user-images.githubusercontent.com/82162107/149837130-bee25724-237b-450b-9bd8-8a6903bcc57c.png)
![image](https://user-images.githubusercontent.com/82162107/149837180-e06ab181-0188-4007-ba67-08cb2a2a790a.png)

**Comment by Vek17** [comment]
At level 6 your weapon damage becomes 1d8 while it is active and that is
what your sheet is showing. This is not extra damage ontop of you normal
weapon damage but is instead a replacement.

**Comment by Vexthecollector** [comment]
:|
Guess I misunderstood. Thank you!
