### ISSUE TITLE
Combat Reflexes (Mythic) seems to make a lot of other effects redundant.

### ISSUE THREAD

**Issue by Imataruto** [Vek17/WrathMods-TabletopTweaks#369]
**Is your feature request related to a problem? Please describe.**
To effects like Ever Ready, normal Combat Reflexes, and Clemency of Shadows, Combat Reflexes (Mythic) gives a feeling of both weakening them and being an overpowered mythic feat.

**Describe the solution you'd like**
I think it's the same case as Armor Master mythic ability, the original gave too much power from the start and from just itself, and a scalable homebrew alternative was added.
Something homebrew like increasing your attacks of opportunity by half your mythic levels would fit much better imo.

**Comment by Vek17** [comment]
> I think it's the same case as Armor Master mythic ability, the original gave too much power from the start and from just itself, and a scalable homebrew alternative was added.

This is interesting becasue this was largely changed for feeling to weak to most people.

Personally I am not convinced mythic combat reflexes is generally strong, and instead it seems fairly niche to me. It also in no way competes with Ever Ready as that adds HUGE to hit and damage bonuses to AoOs.

**Comment by Imataruto** [comment]
actually, you're right. maybe I was overthinking a situation that would need that much attacks of opportunity.
