### ISSUE TITLE
Metamagic Stacking fix seems to break crusade mode's spell damage indicator

### ISSUE THREAD

**Issue by Imataruto** [Vek17/WrathMods-TabletopTweaks#375]
**Describe the bug**
While Metamagic Stacking is on, the damage indicator seems broken

**To Reproduce**
1. Select scorching ray while on a crusade battle
2. Hover over the enemy
3. See incorrect damage indicator

**Expected behavior**
It should not be 0, the enemy is not immune, and the correct damage should be shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/66865165/150815159-4bb7da9e-3491-43af-825c-f4b5c39d0a68.png) metamagic fix off
![image](https://user-images.githubusercontent.com/66865165/150815290-93a07638-08d8-4a6c-bdbe-b42f6843d426.png) metamagic fix on

**Additional context**
My general's power during the bug was 31, if it matters.

**Comment by Vek17** [comment]
Interesting, Will look into this. Likely some change in damage calculation happened in a patch and I didn't notice.

**Comment by Vek17** [comment]
Think I found the issue, should be fixed in the next release
