### ISSUE TITLE
Focused weapon post v1.11.1 with 1.2 Beta patch

### ISSUE THREAD

**Issue by gnunn1** [Vek17/WrathMods-TabletopTweaks#387]
**Describe the bug**
I have a 13 level fighter with focused weapon feat dual wielding scimitars, the scimitars are showing as 1d6 in the inventory and combat log rather then the expected 1d10. I could have sworn this was working correctly pre 1.2 Beta patch.

**Expected behavior**
Fighter using scimitars should be showing 1d6 damage instead of 1d10, I have attached a couple of screenshots, if you need more let me know.

**Screenshots**

![20220129013211_1](https://user-images.githubusercontent.com/9358238/151642952-2617d298-9bcb-41c7-9b0f-65d850b9eaa0.jpg)
![20220129014728_1](https://user-images.githubusercontent.com/9358238/151642957-85afaa4f-77e6-4fd8-a225-dfedce180a19.jpg)

**Additional context**

**Comment by Vek17** [comment]
In your screen shot you do not have focused weapon turned on, can you confirm that the ability is on? This is working in my test game.

**Comment by gnunn1** [comment]
Thanks, I turned it on and it works as you stated. I'll close this bug and give my head a shake.

Just curious though why would this be a toggle, what's the downside to having it active?

**Comment by Vek17** [comment]
In some cases a weapon may have a large die than the current fighter level would provide with focused weapon, for example a great sword starts at 2d6 so until level 20 you are better off with focused weapon off.
