### ISSUE TITLE
Vital strike incorrectly changed to precision damage in 1.2

### ISSUE THREAD

**Issue by Shodan14** [Vek17/WrathMods-TabletopTweaks#398]
**Is your feature request related to a problem? Please describe.**
The 1.2 beta changelog says: 

_Vital Strike damage didn't count as precision damage - fixed;_

**Describe the solution you'd like**
Change vital strike back to be non-precision damage [as in the rules](https://www.d20pfsrd.com/feats/combat-feats/vital-strike-combat/).

**Comment by Vek17** [comment]
This only refers to rowdy damage and vital strike was fixed in TTT AGES ago
