### ISSUE TITLE
Crash in Marquet Square

### ISSUE THREAD

**Issue by JJMAIHEM** [Vek17/WrathMods-TabletopTweaks#40]
Playing under the 1.0.2g version with the mod updated I got a crash in this zone near Curl or the zone where the zombies and shadows are. I asked a friend without the mod to test these zones in the same version of the game and he haven't got any crash.

**Comment by Vek17** [comment]
Would need log to determine if this is released but I highly doubt it is

**Comment by Crowhazard** [comment]
I went there and got no crash at all with the mod enabled (1.08) version 1.0.2g too
