### ISSUE TITLE
Is Armor Master (Light Armor Master) working?

### ISSUE THREAD

**Issue by Sikosh1999** [Vek17/WrathMods-TabletopTweaks#41]
Sorry, this wasnt a bug at all, answered my own question. Please delete :)

**Comment by Vek17** [comment]
This looks like a bug but not sure if it is from the mod. Your max dex mod
is stuck a +3 so i am guessing there is some ghost armor on your character
somehow. I know I saw this in beta but i thought it had been resolved.

**Comment by Edalwulf** [comment]
It's not a bug. Chainmail is Medium Armor. He's not wearing a Chain Shirt, but Chainmail.
Mithril doesn't change the type of armor, it just makes it act like 1 type lighter for the purposes of armor penalties.

**Comment by Vek17** [comment]
Mithril makes it count as light for all purposes except proficiency, even so they are getting +3 from dex instead of +4 even then. Though that could be encumberece.

**Comment by Edalwulf** [comment]
It doesn't for things that specifically target a type of armor. If it says "expert in light armor" (I can't remember, and the screenshots were deleted) then a chain *shirt* works. Chainmail, even mithril, doesn't.

**Comment by Sikosh1999** [comment]
It was encumbrance in this case, thanks everyone!
