### ISSUE TITLE
Error when removing mod

### ISSUE THREAD

**Issue by mjones1052** [Vek17/WrathMods-TabletopTweaks#46]
Getting errors when removing the mod. Happens when going to load a game. I can't load any of the saves unless the mod is turned on, even ones saved before turning on the mod.

<img width="831" alt="Untitled" src="https://user-images.githubusercontent.com/248409/132997913-c95e2947-af40-47ca-a4a3-0642948f6b31.png">

**Comment by Velgus** [comment]
Can't be helped - already explained in the description of the mod:

> Once a game is saved with this mod is enabled it will likely require this mod to be present to load so do not remove or disable the mod once enabled. You can however disable any feature of the mod at will without breaking saves.

**Comment by Vek17** [comment]
This is working as expected. The mod creates a dependency on save.
