### ISSUE TITLE
Eldritch Scion can't take a second bloodline.  (Mythic ability)

### ISSUE THREAD

**Issue by Climhazzard1** [Vek17/WrathMods-TabletopTweaks#48]
I couldn't really tell if this is intended or not from reading the notes.  Eldritch Scion can't take a second bloodline with their mythic ability.  They normally can in the base game.

Even though I can take a level of Dragon disciple to enable the option to get a second bloodline, and intend to for my build, it's awkward because I need to start with the elemental bloodline for it to be the most playable, but can't because then I don't qualify for Dragon disciple.

**Comment by Vek17** [comment]
I'll look into it this evening, they should qualify but owlcat may have made a change here that broke it.

**Comment by Vek17** [comment]
This will be fixed in the next release
