### ISSUE TITLE
Vital Strike for ranged weapons

### ISSUE THREAD

**Issue by Majber** [Vek17/WrathMods-TabletopTweaks#5]
It would be nice to have possibility for Vital Strike for ranged weapons.

**Comment by B14d3r11** [comment]
Seconded! I am trying to play a Rowdy Rogue with a Longbow for that sweet +2d6 sneak attack Vital Strike XD

**Comment by Majber** [comment]
> Seconded! I am trying to play a Rowdy Rogue with a Longbow for that sweet +2d6 sneak attack Vital Strike XD

I want to do same thing 😁😁

**Comment by B14d3r11** [comment]
> 
> 
> > Seconded! I am trying to play a Rowdy Rogue with a Longbow for that sweet +2d6 sneak attack Vital Strike XD
> 
> I want to do same thing 😁😁

I noticed a fix that says "Fixes vital force" what is the fix from the base game?

**Comment by Majber** [comment]
aparently done by Owlcat
