### ISSUE TITLE
Natural armor change breaks Icy Protector

### ISSUE THREAD

**Issue by AeonicAssembler** [Vek17/WrathMods-TabletopTweaks#50]
The Icy Protector ring does two things: grant cold resistance 10, and grant a +2 natural armor bonus if you have the Iceplant hex. However, with the change to natural armor stacking, the bonus conflicts with Iceplant's own bonus, so that function effectively does nothing.
Solution 1: Remove the additional natural armor bonus and the reference to it in the description, making Icy Protector just a cold resistance ring. You may or may not wish to change its price if this is done.
Solution 2: If you want to keep the bonus, change it so the ring increases Iceplant's bonus by 2 rather than providing a separate bonus.

**Comment by Vek17** [comment]
This already should give you a +4 natural armor bonus if you have ice plant. If that isn't working it is a bug, though you can try equiping and unequiping it.

I still need to do a larger natural armor pass, but this should already be fixed.

**Comment by Velgus** [comment]
This is based off memory from a couple days ago, but I seem to recall it working fine using this mod.

**Comment by Amariithynar** [comment]
Can confirm that the ring doesn't work. Equipping it while Camellia has Iceplant results in it simply adding the +2 from Iceplant. The tooltip similarly only indicates +2 Iceplant, with nothing else.

**Comment by kbomb69** [comment]
I can confirm that Icy Protector _does_ work with the natural armour stacking fixes enabled. This seems to be a visual error similar to something like Aspect of Kalavakus not appearing on the number breakdown.

**No Icy Protector equipped** 
![Wrath_Eot8nkrCSo](https://user-images.githubusercontent.com/88919301/133954727-79a2af2a-4a1a-4a52-9ed4-2a2a62eba487.png)
**Icy Protector equipped**
![Wrath_bhiLxjCdz9](https://user-images.githubusercontent.com/88919301/133954786-578c60e3-9d44-48d8-a82c-8b04c1b9d175.png)

**Comment by polivierstpch** [comment]
@kbomb69 If you notice in the second picture, Total AC does go to 44 from 42. It just doesn't change the Iceplant value. I guess it does this as default in the base game too, if anyone can confirm.

**Comment by Amariithynar** [comment]
AHA! You are correct, @kbomb69. I wasn't as thorough in testing as I should have been and did not notice that the actual value was changing, as I was expecting the value for Iceplant listed to also change, or for at least there to be a separate "+4 Icy Protector" listed instead of Iceplant.

**Comment by Vek17** [comment]
Interesting, the tool tip should read +4 Icy protector. There has been some changes to how tooltips are written that may have broken this.
