### ISSUE TITLE
Feature Request: Armor Mastery Prereqs disable setting option

### ISSUE THREAD

**Issue by AlexClark** [Vek17/WrathMods-TabletopTweaks#53]
Taking three mythic abilities to uncap your dex modifier for heavy armor seems excessive for non-arcane casters in particular. It would be nice to have an option to disable the light/med prereqs for the abilities so you can pick up the armor type of your choice without spending almost all of your ability picks on it.

**Comment by Vek17** [comment]
I'd recommend using an other mod to bypass prerequisites, but you only need medium for Mithril Plate.
