### ISSUE TITLE
TabletopTweaks not available in Unity mod manager

### ISSUE THREAD

**Issue by kenshiotagi** [Vek17/WrathMods-TabletopTweaks#54]
Hi !
I love the way this mod going, allowing us better mythic path or character customization.

BUT...

UnityMod Manager successfully unpacked Tabletop Tweaks, but its status in none existent (while ToyBox shows "available"), therefore when I launch WOTR, UnityMod Manager only shows ToyBox and I can't profit from your mod. (I've verify in game)

Is it because I've got a cracked version of WOTR or because game is in French (who likes french anyway?)

New to mod and crpg btw, but thanks for your time & work.

**Comment by Vek17** [comment]
I am guessing you downloaded the source and not the release. Try the release page and download the modzip not the source code

https://github.com/Vek17/WrathMods-TabletopTweaks/releases

**Comment by Goldiniana** [comment]
It does not work in the Russian version of the game. Yes, Zipa downloaded an archive designed for installation through UMM 
![изображение](https://user-images.githubusercontent.com/90867921/133674471-484fed31-11ac-4a34-960c-01cc14dbb5b0.png)
He is in the game itself, but not unfolding, unlike toybox.

**Comment by Vek17** [comment]
Unlike toybox there is nothing to unfold. Configuration is handled extreanally in the user settings folder and other than that it just runs.
