### ISSUE TITLE
(Fix Suggestion) Fast Movement being penalized by medium armor

### ISSUE THREAD

**Issue by pootthedestroyer** [Vek17/WrathMods-TabletopTweaks#55]
What it says on the tin. The Fast Movement ability description specifically says that you can be wearing medium armor so long as you're not encumbered or otherwise hindered. Well, it's not working like that in the game.

I double-checked on an old save with no mods running, so it's not a TT or other mod issue.

If it helps narrow anything down: mithral medium armor does work properly with the ability (as it obviously should, since it should be counted as light armor in the background.) I am not able to test mithral heavy armor in my current games.

**Comment by Vek17** [comment]
Which class is this specificly?

**Comment by pootthedestroyer** [comment]
I ran into it personally with a Primalist Bloodrager.

**Comment by pootthedestroyer** [comment]
Checked with Barbarian today, and the same bug exists.

For some reason, the game uses two separate background abilities for "barbarian" Fast Movement: one for Bloodrager, and one for Barbarian. Both have the exact same rules (according to their descriptions,) and both are bugged in the same way: non-Mithral Medium Armors attach a -10 movement penalty.

**Comment by Vek17** [comment]
So I am not seeing anything that should negate the medium armor penalty to speed here. You should have the -10 from the armor and +10 from fast movement in medium armor.

**Comment by pootthedestroyer** [comment]
I just checked the PnP rules again, and it seems you are correct. Medium Armor does impose a speed penalty all by itself regardless of stats, encumbrance, or the Fast Movement ability itself.

That's my mistake on the PnP rules. Sorry.
