### ISSUE TITLE
Consider adding better alignment changes (feature request)

### ISSUE THREAD

**Issue by Mosulvet** [Vek17/WrathMods-TabletopTweaks#57]
Similar to: https://www.nexusmods.com/pathfinderwrathoftherighteous/mods/104?tab=files&file_id=432

**Comment by Amariithynar** [comment]
Actually against this change. Taking neutral good options should shift you towards neutral good. Only if they're lawful good should you shift towards lawful AND good.

**Comment by Vek17** [comment]
This feels out of scope, while it seems like a good feature I do want to
prevent this mod from becoming a full omnibus.
