### ISSUE TITLE
Issue with crusade unit damage?

### ISSUE THREAD

**Issue by NordicRest** [Vek17/WrathMods-TabletopTweaks#7]
While I can't confirm that this mod is the issue, I only started experiencing this bug after installing it.

Crusade units are doing far less damage than expected (e.g. Archers should've dealt 192d6+960 * 1.1 damage to a unit without DR, dealt 77 damage, which is about 20x less than the expected minimum of ~1260 damage). This affects all allied units, though not enemy units.

**Comment by Vek17** [comment]
Are you accounting for the tactical combat modifier? My numbers are looking correct both with and without the parts that touch damage calculations enabled. Damage is super low in the crusade now though but I think that is a result of Owlcat.

If you disable MetamagicStacking you can disable all my changes to the damage system.

**Comment by LangyMD** [comment]
Apparently the Training Grounds multiply damage by 0.1 instead of 1.1, which could explain this: https://www.reddit.com/r/Pathfinder_Kingmaker/comments/pj6u4k/psa_regarding_crusade_mechanics_dont_build/

**Comment by Vek17** [comment]
I pushed a patch regarding training grounds, if that was the issue then it should now be resolved

**Comment by NordicRest** [comment]
So, this is now _actually_ an issue with TTT: Training grounds reduce unit damage output by 10% rather than increase.

Hellknights do not have Training Grounds, Headhunters do.

https://steamcommunity.com/sharedfiles/filedetails/?id=2606370376
https://steamcommunity.com/sharedfiles/filedetails/?id=2606370352
