### ISSUE TITLE
Info Request: One Handed Weapon toggle

### ISSUE THREAD

**Issue by Skarm-Ghelmaad** [Vek17/WrathMods-TabletopTweaks#75]
Forgive me, but I wanted to understand just one thing:

What is the **exact effect** of the **one handed weapon toggle**?

Let's say I managed to get an **Elven Curve Blade**...can I use it one-handed?

...and...would I get a penalty?

...if so...what penalty would I have?

...can I dual wield two Elven Curve Blades with it? 

Or is it only for very specific weapons (i.e., Bastard Sword)?

Thanks,
Skarm

P.S.: While obviously I'd be fully satisfied with your explanation....since it is a new special toggle, would be possible to add some extra info about it in the readme?

( Frankly I loved the idea of creating a character that took advantage of it, but I was a bit  worried I might have misunderstood how it worked, so I ended up creating a character who was focused on one-handed weapons...however, since the **elven curved blade** looked like a katana in Pathfinder Kingmaker and the dueling sword no longer looks like a katana, I was really curious if that would work with that weapon...even with some penalty!! 🤔)

**Comment by TKDancer** [comment]
i THINK its a toggle so u force your character to use weapons that can ALREADY be used in 1 hand to be used in 1 hand instead of being used as a 2-handed weapon when the off-hand is empty
