### ISSUE TITLE
Dragonkind Spells and Scrolls fail

### ISSUE THREAD

**Issue by s4mburke** [Vek17/WrathMods-TabletopTweaks#8]
When using this mod the Dragonkind of spells fail both Spells, scrolls and abilities.

**Comment by Vek17** [comment]
Looks like this is Dragonkind 1 and 2 that fail. They are configured as having their breath as a separate polymorph and that is what is breaking things. Patch will be out shortly.

That said to bypass completely you can disable the polymorph stacking fixes in Fixes.Json

**Comment by Vek17** [comment]
This has been patched
