### ISSUE TITLE
Request - loremaster fix

### ISSUE THREAD

**Issue by templer10** [Vek17/WrathMods-TabletopTweaks#84]
Hi could you please fix loremaster to not lose a casting level at first level and to add the spell secrets? Thanks

**Comment by Pokora22** [comment]
Since the loremaster level lost was fixed in 1.2, is there a way to recover the lost caster level without respeccing (and losing copied spells)?

**Comment by Vek17** [comment]
This has been fixed

**Comment by Pokora22** [comment]
![image](https://user-images.githubusercontent.com/26257634/134644432-9be674da-2bd7-465a-8a82-e0afde4c6d50.png)
Has it... ?

Character that previously lost the level will not recover them. That's what I'm saying. Would need to reset and respec - which in case of wizard causes them to lose copied spells.

**Comment by Vek17** [comment]
There isn't a clean way to retroactively fix a messed up character, the easiest way fro you to deal with this if you have the issue is via toybox. That said all new loremaster picks will gain CL.
