### ISSUE TITLE
Wolf-Scarred Face Oracle Curse does not grant a bite attack.

### ISSUE THREAD

**Issue by Laurgrin** [Vek17/WrathMods-TabletopTweaks#88]
Before installing this mod, I would get an extra bite attack. After installing this mod, I do not. Respecing does not help.

**Comment by pheonix99** [comment]
Works just fine for me.

**Comment by Vek17** [comment]
what features and mods are at use here?

**Comment by Laurgrin** [comment]
![image](https://user-images.githubusercontent.com/15212775/134376510-9d04753a-8308-41bd-b0cf-9cbeb8fb789d.png)
In the mod settings, only changed here:
![image](https://user-images.githubusercontent.com/15212775/134376820-4719293d-63ba-42c5-ba0d-65995542a0b8.png)

**Comment by Laurgrin** [comment]
Recent update fixed the issue.

**Comment by pheonix99** [comment]
Experiencing this now at level five, known base game bug is involved.
