### ISSUE TITLE
Could you add Eldritch Scion to the compatability list for Bloodline Ascendance?

### ISSUE THREAD

**Issue by jumpsteadeh** [Vek17/WrathMods-TabletopTweaks#89]

**Comment by Vek17** [comment]
Does this not already work? I'll have to check but off the top of my head it should.

**Comment by jumpsteadeh** [comment]
![blubliansm](https://user-images.githubusercontent.com/91145735/134261581-c53c5ec0-95d3-47fa-838b-65de00d0fce2.png)  
  
This is what it shows me. I have 4 levels of ES and 3 of Dragon Disciple, with the red dragon bloodline. I haven't checked vanilla, but I can't imagine that 2nd requirements table is supposed to be there at all. Sorry for not having a screenshot the first time.

**Comment by jumpsteadeh** [comment]
> 
> 
> Does this not already work? I'll have to check but off the top of my head it should.

**Comment by jumpsteadeh** [comment]
thanks
